apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: rbmjbae/argrocd-test:4.0
        ports:
        - containerPort: 8080
