 {{- $env := .Values.env -}}
apiVersion: v1
kind: Service
metadata:
  name: rbm-order-svc-{{ $env }}
spec:
  selector:
    app: rbm-order-depl-{{ $env }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
