apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbm-order-depl
spec:
  selector:
    matchLabels:
      app: rbm-order-depl
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: rbm-order-depl
    spec:
      containers:
      - name: rbm-order-depl
        image: rbmjbae/argrocd-test:4.0
        ports:
        - containerPort: 8080
